name: Generate Deployable Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9  # या जो भी pnpm वर्जन आप यूज़ कर रहे हों

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Project
        run: pnpm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/
